logRootDir: /tmp
logging:
  config: classpath:log4j2-srv.xml

# Rabbit MQ配置
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /warning-system
    username: jinzhaosn
    password: jinzhaosn123