server:
  port: 8080

spring:
  profiles:
    active: @profiles.active@
  application:
    name: warning-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/warning_system?useUnicode=true&characterEncoding=UTF-8&autoConnect=true&rewriteBatchedStatements=true
    username: root
    password: jinzhaosn123

# 服务名称
service:
  position:
    systemName: Function-Points-System
    serviceGroup: Warning-System
    serviceName: ${spring.application.name}
    serverPort: ${server.port}